nome = str(input('Digite seu nome completo: ')).strip()
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} lteras'.format(len(nome)- nome.count(' ')))
print('Seu primeiro nome tem ao todo {} letras'.format(nome.find(' ')))
